""" "from code"

Revision ID: 68835d2662c7
Revises: 
Create Date: 2018-05-01 17:50:58.191382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68835d2662c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('preco', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('permissao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('is_finalizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compra')
    op.drop_table('usuarios')
    op.drop_table('item')
    # ### end Alembic commands ###
